#+setupfile: ~/.config/hax-config/emacs/latex-export-header.org
#+author: Артемов Максим ИВБО-02-18
#+title: "Учебный эмулятор центрального процессора"
#+options: toc:nil

Разработать графическое приложение, позволяющее детально изучить принципы
работы процессора на архитектуре x86. Данная программа предназначена для
использования в образовательных программах по таким предметам как
"Микропроцессорные системы", "Структура операционных устройств" и
"Архитектура вычислительных машин и сетей".

Программа будет реализована на языке С++ с использованием Qt.

В качесве примера примера процессора будет использована модель i386, в виду
наличия достаточно богатого функционала (по сравнению с более старыми
моделями, такими как i8080) для демонстрации значительной части принципов
работы реального процессора. Более современные модели выбраны не были в
связи с значительным увеличением сложности реализации (маловероятно что
дипломную работу можно будет выполнить в срок).

Планируемый функционал включает в себя пошаговое исполнение комманд
процессора, мониторинг состояния регистров различного вида, компиляция
пользовательского кода на ассемблере в машинные инструкиции (или ручной
ввод машинных инструкций напрямую в память эмулятора).
