name:
  build
on:
  push
jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, 'SKIP')
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install graphviz
      - uses: actions/checkout@v2
      - uses: alaviss/setup-nim@master
        with:
          path: '../nim'
          version: 'version-1-4'
      - run: "nimble -y test"
