name: test
on: push
jobs:
  test:
    if: |
      !contains(github.event.head_commit.message, 'WIP')

    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get install -y libx11-dev libgl1-mesa-dev xorg-dev

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: |
          wget https://nim-lang.org/download/nim-1.6.0-linux_x64.tar.xz
          tar xf nim-1.6.0-linux_x64.tar.xz
          export PATH="$PWD/nim-1.6.0/bin:$PATH"

          git clone --recursive https://github.com/cimgui/cimgui.git
          pushd cimgui
          cmake .
          make -j12
          sudo cp cimgui.so /usr/lib/cimgui.so
          popd

          echo $PATH
          nim --version
          ./build.sh
