name: test
on: push
jobs:
  test:
    if: |
      !contains(github.event.head_commit.message, 'WIP')

    strategy:
      matrix:
        nim: ["version-1-6"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: alaviss/setup-nim@master
        with:
          path: "../nim"
          version: ${{ matrix.nim }}
      - run: "nim --version"
      - run: "./build.sh"
