name: test
on: push
jobs:
  test:
    if: |
      !contains(github.event.head_commit.message, 'WIP')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: alaviss/setup-nim@master
        with:
          version: "version-1-6-0"
          path: "nim"
      - run: "nim --version"
      - run: "./build.sh"
